export const namedKeys = {
	ArrowDown: 'ArrowDown',
	ArrowRight: 'ArrowRight',
	ArrowUp: 'ArrowUp',
	ArrowLeft: 'ArrowLeft',
	Backspace: 'Backspace',
	Delete: 'Delete',
	Tab: 'Tab',
	Shift: 'Shift',
	Escape: 'Escape',
	a: 'a',
	A: 'A',
	p: 'p',
	P: 'P',
}
